spring:
  thymeleaf:
    mode: HTML
    encoding: utf-8
    servlet:
      content-type: text/html
    suffix: .html
    cache: false
    cahche:
      chain:
        strategy:
          content:
            enabled: true
            paths: /**
    prefix: classpath:/templates/
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
server:
  port: 8080
  servlet:
    context-path: /localmachine