spring:
  thymeleaf:
    mode: HTML
    encoding: utf-8
    servlet:
      content-type: text/html
    suffix: .html
    cache: false
    cahche:
      chain:
        strategy:
          content:
            enabled: true
            paths: /**
    prefix: classpath:/templates/
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
server:
  port: 8080
  servlet:
    context-path: /localmachine

xncoding:
  socket-port: 9099    #socket端口
  ping-interval: 60000 #Ping消息间隔（毫秒）
  ping-timeout: 180000 #Ping消息超时时间（毫秒）